version: '2.4'

services:
  frontend:
    build:
      context: ../../../quote-of-the-day_react
      args:
        REACT_APP_BFF_ENDPOINT: localhost:8080
    image: ci.odd-e.com:5000/quote-of-the-day_react
    ports:
      - "3000:80"
    links:
      - bff
  bff:
    build:
      context: ../../../quote-of-the-day_bff
    image: ci.odd-e.com:5000/bff
    ports:
      - "8080:8080"
    links:
      - backend
  backend:
    build:
      context: ../../../quote-of-the-day_backend
    image: ci.odd-e.com:5000/backend
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
